server:
  port: 8083
  servlet:
    context-path: /web
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name:  com.mysql.jdbc.Driver
      url: jdbc:mysql://140.200.0.130:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: Aa123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-password: druid
        login-username: druid
      filter:
        stat:
          log-slow-sql: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: net.cnway.mybatis
