server:
  port: 8082
  servlet:
    context-path: /web
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://140.200.0.130:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Aa123456
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: net.cnway.mybatis